### ISSUE TITLE
Exception in client

### ISSUE THREAD

**Issue by Constri** [callFEELD/BoardGame-Detection#9]
`Traceback (most recent call last):
  File "main.py", line 354, in <module>
    main()
  File "main.py", line 105, in main
    DIFFICULTY = check_configuration()
  File "/home/pi/server/ip_client.py", line 92, in check_configuration
    pieces, _ = client.detect(options=options)
  File "/home/pi/server/src/client.py", line 130, in detect
    json
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/pi/server/src/client.py", line 92, in _request
    json=json) as resp:
  File "/home/pi/.local/lib/python3.7/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/home/pi/.local/lib/python3.7/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/home/pi/.local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 860, in start
    self._continue = None
  File "/home/pi/.local/lib/python3.7/site-packages/aiohttp/helpers.py", line 596, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError`

**Comment by Constri** [comment]
Found the issue. This only occurs when you watch the stream at the same time.
Close the stream and will work. It is also much faster.
